#First build dockerfile using tag audience:1.0 and then run docker-compose up -d

version: "3.3"

networks:
  bridge:
    driver: bridge

services:
  jobmanager:
    image: audience:1.0
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      bridge:
        aliases:
          - jobmanager

  taskmanager:
    image: audience:1.0
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=1
    networks:
      bridge:
        aliases:
          - taskmanager

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    depends_on:
      - taskmanager
    networks:
      bridge:
        aliases:
          - zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CREATE_TOPICS: "kafkaFlinkTest:1:1"
    networks:
      bridge:
        aliases:
          - kafka